---

- name: Set Max CPU for K8s VMs
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config --maximum
  with_items:
    - { vm: "{{master1}}", cpu: '4' }
    - { vm: "{{master2}}", cpu: '4' }
    - { vm: "{{master3}}", cpu: '4' }
    - { vm: "{{node1}}", cpu: '2' }
    - { vm: "{{node2}}", cpu: '2' }

- name: Set Usable CPU for controller and compte VMs
  command: virsh setvcpus "{{ item.vm }}" "{{ item.cpu }}" --config
  with_items:
      - { vm: "{{master1}}", cpu: '4' }
      - { vm: "{{master2}}", cpu: '4' }
      - { vm: "{{master3}}", cpu: '4' }
      - { vm: "{{node1}}", cpu: '2' }
      - { vm: "{{node2}}", cpu: '2' }
