---

- name: Create VMs for K8s cluster using Ubuntu16.04 template
  command: virt-clone -o "{{ubuntu_template}}" -n "{{item}}" -f "{{vms_disk_path}}"/"{{item}}".qcow2
  with_items:
      - "{{master1}}"
      - "{{master2}}"
      - "{{master3}}"
      - "{{node1}}"
      - "{{node2}}"
  ignore_errors: false


#  - name: Modify domain connection socket in XML file for RHEL host
#    shell: sed -i -e 's/domain-"{{centos_template}}"/domain-"{{item}}"/g' /etc/libvirt/qemu/"{{item}}".xml
#    replace:
#      path: /etc/libvirt/qemu/"{{item}}".xml
#      regexp: '(\s+)domain-"{{centos_template}}"(\s+.*)?$'
#      replace: '\1domain-"{{item}}"\2'
#      backup: yes
#    with_items:
#      - "{{master}}"
#      - "{{node1}}"
#      - "{{node2}}"
#    when: ansible_os_family == "RedHat"
