---

- name: Copy interfaces configuration files and hosts file to KVM host to copy to VMs
  template:
    src: "{{item}}"
    dest: /var/tmp/
    owner: root
    group: root
    mode: 0644
  with_items:
    - k8s-master1.interface.j2
    - k8s-master2.interface.j2
    - k8s-master3.interface.j2
    - k8s-node1.interface.j2
    - k8s-node2.interface.j2
    - hosts_file.j2
  ignore_errors: false
