---

- name: Reboot all VMs
  shell: for i in `cat /var/tmp/k8s_domain`;do virsh reboot $i;done

- name: Wait for VMs to come up after Reboot
    pause:
    mintues: 2
    prompt: "Please hold for 2 minutes, VMs are coming up. Then use Ctrl+c and then c, to continue playbook"

- name: After reboot do validation
  shell: ssh -o StrictHostKeyChecking=no root@"{{item}}" hostname >> /var/tmp/guest_hostname
  with_items:
    - "{{master1_ip}}"
    - "{{master2_ip}}"
    - "{{master3_ip}}"
    - "{{node1_ip}}"
    - "{{node2_ip}}"

- name: List guest VMs hostname
  shell: cat /var/tmp/guest_hostname
  register: guest_hostname

- debug:
    var: guest_hostname.stdout
