---

- name: Create master VMs snapshot
  command: virsh snapshot-create-as "{{item}}" "{{item}}"-all-predone
  with_items:
    - "{{master1}}"
    - "{{master2}}"
    - "{{master3}}"
  ignore_errors: false

- name: List master VMs snapshot
  shell: virsh snapshot-list "{{item}}"
  with_items:
    - "{{master1}}"
    - "{{master2}}"
    - "{{master3}}"
  register: master_snapshot_list

- debug:
    var: master_snapshot_list.stdout
